### PR TITLE
add logo as svg

### PR DESCRIPTION
**Pull request by schwesig**
add logo as svg

Font
- OP1ST>> : ?
- #b4mad : EngraversGothic BT ?

Color
- OP1 : #b3b3b3
- ST>> : #ffcc00
- #b4mad : #698b69 (DarkSeaGreen4)

### CODE REVIEW

**Comment by schwesig** [comment]
fyi
/cc @goern
/cc @durandom

**Comment by durandom** [comment]
@schwesig do you also want to replace the img in the readme? or where should this SVG be used?

**Comment by schwesig** [comment]
> @schwesig do you also want to replace the img in the readme? or where should this SVG be used?
@durandom 

basic idea. having an SVG for future use and to scale is always better as a source, no matter if we use it right now.

But yes, we can replace it too.

**Comment by schwesig** [comment]
logo in README changed to SVG

**Review by durandom — APPROVED** [review]
❤️

**Pull request merged**
